version: '3.6'
 
services:
 
  pdb:
    image: postgres
    container_name: postgres_test
    restart: always
    environment:
      POSTGRES_PASSWORD: postgrespassword
    ports:
      - 6543:5432
    volumes:
      - ./db-data:/var/lib/postgresql/data
  adminer:
    image: adminer
    container_name: adminer_test
    depends_on:
      - pdb
    restart: always
    ports:
      - 8080:8080
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_test
    depends_on:
      - pdb
    ports:
      - 7070:80
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: unless-stopped